controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm:
      type: position_controllers/JointGroupPositionController

left_arm:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - l1l_to_base_link
      - l2l_to_l1l
      - l3l_to_l2l
      - l4l_to_l3l
      - l5l_to_l4l
      - l6l_to_l5l

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort