controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster: 
      type: joint_state_broadcaster/JointStateBroadcaster 
    
    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_gripper_controller:
      type: position_controllers/GripperActionController

    right_gripper_controller:
      type: position_controllers/GripperActionController

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    joints:
      - l1l_to_base_link
      - l2l_to_l1l
      - l3l_to_l2l
      - l4l_to_l3l
      - l5l_to_l4l
      - l6l_to_l5l
      - l1r_to_base_link
      - l2r_to_l1r
      - l3r_to_l2r
      - l4r_to_l3r
      - l5r_to_l4r
      - l6r_to_l5r
      - l1h_to_base_link
      - l2h_to_l1h
      - g2la_to_g1l
      - g2lb_to_g1l
      - g2ra_to_g1r
      - g2rb_to_g1r
    publish_rate: 50

left_arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - l1l_to_base_link
      - l2l_to_l1l
      - l3l_to_l2l
      - l4l_to_l3l
      - l5l_to_l4l
      - l6l_to_l5l
    command_interfaces: [position]
    state_interfaces: [position, velocity]

right_arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - l1r_to_base_link
      - l2r_to_l1r
      - l3r_to_l2r
      - l4r_to_l3r
      - l5r_to_l4r
      - l6r_to_l5r
    command_interfaces: [position]
    state_interfaces: [position, velocity]

head_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - l1h_to_base_link
      - l2h_to_l1h
    command_interfaces: [position]
    state_interfaces: [position, velocity]

left_gripper_controller:
  ros__parameters:
    type: position_controllers/GripperActionController
    joint: g2la_to_g1l

right_gripper_controller:
  ros__parameters:
    type: position_controllers/GripperActionController
    joint: g2ra_to_g1r
