controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

head_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - l1h_to_base_link
      - l2h_to_l1h
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_nonzero_velocity_at_trajectory_end: true