# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - l1l_to_base_link
      - l2l_to_l1l
      - l3l_to_l2l
      - l4l_to_l3l
      - l5l_to_l4l
      - l6l_to_l5l
    interface_name: velocity

position_controller:
  ros__parameters:
    joints:
      - l1l_to_base_link
      - l2l_to_l1l
      - l3l_to_l2l
      - l4l_to_l3l
      - l5l_to_l4l
      - l6l_to_l5l
    interface_name: position
